version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"  # Expone UI/API de Zipkin en http://localhost:9411
    networks:
      microservices_network:
        aliases:
          - zipkin

  service-discovery-container:  # Servidor de descubrimiento (Eureka Server)
    image: selimhorri/service-discovery-ecommerce-boot:0.1.0
    ports:
      - "8761:8761"  # UI/endpoint de Eureka en http://localhost:8761
    networks:
      microservices_network:
        aliases:
          - service-discovery-container
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/

  cloud-config-container:  # Spring Cloud Config Server
    image: selimhorri/cloud-config-ecommerce-boot:0.1.0
    ports:
      - "9296:9296"  # Endpoint del Config Server en http://localhost:9296
    networks:
      microservices_network:
        aliases:
          - cloud-config-container
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITY_ZONES_DEFAULT=myzone
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/

networks:
  microservices_network:              # Declaración de la red compartida
    name: microservices_network       # Nombre real de la red en Docker
    driver: bridge                    # Driver 'bridge'
